// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using NUnit.Framework;
using UnityEngine;
using NSubstitute;

namespace sci.tests
{
	public abstract class MediatorTest
	{
		protected GameObject gameObject;

		protected static bool runningFromEditor { get {
			try { return Application.isPlaying || true; }
			catch (Exception e) { return false; }
		}}

		[SetUp]
		public void SetUpMediatorTest() {

			if (!runningFromEditor) {
				Assert.Ignore("These tests can only run in unity");
				return;
			}
			gameObject = new GameObject();
		}

		[TearDown]
		public void TearDownMediatorTest() {
			if (!runningFromEditor) return;
			if (gameObject!=null) {
				GameObject.DestroyImmediate(gameObject);
			}
		}
	}
}

